export const ApiEndpoints = {
  AUTH: {
    BASE: "/api/v1/auth",
    REGISTER: "/register",
    GOOGLE: "/google",
    FORGOT_PASSWORD: "/forgot-password",
    VERIFY_RESET_OTP: "/verify-reset-otp",
    RESET_PASSWORD: "/reset-password",
    VERIFY_OTP: "/verify-otp",
    LOGIN: "/login",
    LOGOUT: "/logout",
    ME: "/me",
    ADMIN_TEST: "/admin-test",
    REFRESH_TOKEN: "/refresh-token",
    RESEND_OTP: "/resend-otp",
  },
  PROVIDER: {
    BASE: "/api/v1/provider",
    ONBOARDING_SUBMIT: "/onboarding/submit",
    ONBOARDING_RESUBMIT: "/onboarding/resubmit",
    PROFILE: "/profile",
  },
  ADMIN: {
    BASE: "/api/v1/admin",
    PROVIDER_APPLICATIONS: "/provider-applications",
    PROVIDER_APPLICATION_DETAILS: "/provider-applications/:userId",
    APPROVE_PROVIDER_APPLICATION: "/provider-applications/:userId/approve",
    REJECT_PROVIDER_APPLICATION: "/provider-applications/:userId/reject",
    SERVICE_PROVIDERS: "/service-providers",
    SERVICE_PROVIDER_DETAILS: "/service-providers/:userId",
    UPDATE_SERVICE_PROVIDER_STATUS: "/service-providers/:userId/status",
    USERS: "/users",
    UPDATE_USER_ACCOUNT_STATUS: "/users/:userId/status",
    CATEGORIES: "/categories",
    UPDATE_CATEGORY: "/categories/:categoryId",
    UPDATE_CATEGORY_STATUS: "/categories/:categoryId/status",
    BLOCK_CATEGORY: "/categories/:categoryId/block",
    UNBLOCK_CATEGORY: "/categories/:categoryId/unblock",
  },
  UPLOAD: {
    BASE: "/api/v1/upload",
    ROOT: "/",
  },
} as const;
